# Generated by Django 3.1.7 on 2022-05-03 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Reord_Order',
        ),
    ]
