# Generated by Django 3.1.7 on 2022-05-03 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20220504_0041'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reord_Order',
            new_name='Record_Order',
        ),
    ]
